apiVersion: v1
kind: Secret
metadata:
  name: transaction-service-secrets
  namespace: ebanking
  labels:
    app: ebanking-transaction-service
type: Opaque
data:
  # Base64 encoded JWT secret (replace with your actual secret)
  JWT_SECRET: eW91ci1zZWNyZXQta2V5LWhlcmUtbWFrZS1pdC1sb25nLWFuZC1zZWN1cmUtaW4tcHJvZHVjdGlvbg==
  # Add other secrets as needed
  # EXCHANGE_RATE_API_KEY: <base64-encoded-api-key>
stringData:
  # Alternative way to specify secrets (not base64 encoded)
  # JWT_SECRET: "your-secret-key-here-make-it-long-and-secure-in-production" 